#!/bin/bash

export FRAMEBUFFER=/dev/fb0

FILE=$1
IDUMP_OPT="-f"
SCREEN_HEIGHT="1024"
MUDRAW_OPT="-o - -F png -h $SCREEN_HEIGHT"

INDEX=1 # page origin:1
PAGES=`mutool info $FILE | grep "^Pages:" | cut -d" " -f2`

tput civis
#tput clear

#echo "filename:$FILE page:$INDEX"
mutool draw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | idump $IDUMP_OPT > /dev/null 2>&1

while :; do
	read -s -n 1 KEY

	#tput clear

	case "$KEY" in
	"w")
		INDEX=`expr $INDEX + 1`;;
	"W")
		INDEX=`expr $INDEX + 10`;;
	"m")
		INDEX=`expr $INDEX - 1`;;
	"M")
		INDEX=`expr $INDEX - 10`;;
	"g")
		INDEX=1;;
	"G")
		INDEX=$PAGES;;
	"q")
		tput cnorm
		exit 0;;
	esac

	if test $INDEX -lt "1"; then
		INDEX=$PAGES
	elif test $INDEX -gt $PAGES; then
		INDEX=1
	fi

	#echo "filename:$FILE page:$INDEX"
	mudraw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | idump $IDUMP_OPT > /dev/null 2>&1
done
